# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         LWP-Simple-WithCache
version:      0.03
version_from: lib/LWP/Simple/WithCache.pm
installdirs:  site
requires:
    LWP::Simple:                   0
    LWP::UserAgent::WithCache:     0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
